# -*- coding: utf-8 -*-
"""Graph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oxgO06q2XjMjNYptj6N198PBh7cUvsiv

GROUP 8 - BM7
*  Acosta, John Paolo Miguel
*  Gonzales, Dave Justine
*  Perez, Ashton Miguel
*  Rupisan, Anthony James
"""

# @title Importing libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv('/content/laptop_price - dataset.csv')

# 1. Dataset Overview
print("First 5 rows of the dataset:")
print(df.head())  # Display the first 5 rows of the dataset

print("\nDataset Information:")
df.info()  # Information about the dataset (types, missing values)

print("\nDescriptive Statistics:")
print(df.describe())  # Summary statistics

print("\nMissing Values in the Dataset:")
print(df.isna().sum())  # Check for missing values

# Value counts for the 'Company' column (example)
print("\nCount of Laptops by Company (All):")
company_counts = df['Company'].value_counts()  # Count the unique values in the 'Company' column
print(company_counts)

# Filter only those with even counts
even_company_counts = company_counts[company_counts % 2 == 0]
print("\nCount of Laptops by Company (Even Occurrences):")
print(even_company_counts)

# @title Mount
from google.colab import drive
drive.mount('/content/drive')

# @title Imports
from google.colab import files
uploaded = files.upload()

# @title Dataset csv
df = pd.read_csv('laptop_price - dataset.csv')

# @title Data Table
from google.colab import data_table
data_table.enable_dataframe_formatter()
data_table.DataTable(df, num_rows_per_page=10)

# @title Info

df.info()

# @title Describe
df.describe()

# @title Sum
df.isnull().sum()

# @title Total company
df['Company'].nunique()
print('The number of brands in Company column is', df['Company'].nunique())
brand_counts = df['Company'].value_counts()
print("There are {} unique brands in the dataset, including:".format(len(brand_counts)))
print(brand_counts)

# @title Histogram
plt.figure(figsize=(10, 6))
sns.histplot(df['Price (Euro)'], bins=20, kde=True, color='blue')
plt.title('Distribution of Laptop Prices in Euro')
plt.xlabel('Price (Euro)')
plt.ylabel('Frequency')
plt.show()

"""
In this histogram is the distribution of laptop prices in euros. One axis displays the price in euros, and the other shows the frequency with which computers fall into each price range. To illustrate the probability distribution of laptop price, a kernel density estimate (KDE) curve is also included on the plot.

    OBSERVASION:
- Most computers appear to be under Є2000, with a notable concentration in the Є500-Є1500 range.


- The KDE curve peaks in this price range, indicating that most customers are probably buying laptops in this range.


- There are some laptops that are priced much higher, above Є2500, but these are less frequent, as shown by the sharp drop in frequency on the right side of the histogram.


- This trend makes sense since high-end or luxury models such as gaming or business laptopsare more uncommon, while the most popular laptops for daily use, students, etc. tend to be in the mid-range price bracket."""

# @title Scatter Plot
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='RAM (GB)', y='Price (Euro)', hue='Company', palette='Set2')
plt.title('Laptop Price vs. RAM (GB)')
plt.xlabel('RAM (GB)')
plt.ylabel('Price (Euro)')
plt.show()

"""The correlation between RAM capacity and laptop costs across various businesses can be effectively analyzed using a scatter plot. With that, stakeholders can learn how RAM affects pricing and how businesses differentiate their products in the market by seeing this relationship graphically. Both customers evaluating value for money and businesses planning their product features, prices, and market positioning can benefit from this research. In along with showing trends, the scatter plot illustrates the variety of laptop market product offerings and price approaches.

    OBSERVASION:
- The scatter plot, broken down by company, shows the association between laptop costs and RAM capacity. To do more understanding of the interactions between these two variables is made possible by this graphical portrayal.  Potential gaps in offerings may indicate opportunities for new products.

- The scatter plot reveals a positive correlation between RAM (GB) and price (Euro), that suggesting that laptops with more RAM are priced higher. Companies are represented by distinct colors, allowing for easy identification of pricing strategies with a variability in prices is evident, indicating factors like CPU performance, design, brand reputation, and additional features. Outliers may be high-RAM or low-RAM models priced lower than expected. That make sure market segmentation is evident, with high-end brands targeting gamers or professionals, while others focus on affordability.


"""

# @title Box Plot Graph,
df.rename(columns={'Price (Euro)': 'Price_Euro'}, inplace=True)
plt.figure(figsize=(12, 6))
sns.boxplot(data=df, x='Company', y='Price_Euro')
plt.title('Laptop Prices by Company')
plt.xlabel('Company')
plt.ylabel('Price (Euro)')
plt.xticks(rotation=45)
plt.show()

"""A useful tool for figuring out how different companies charge different amounts for laptops is the box plot. Through the display of the distribution, median, and outliers, interested parties can learn more about market patterns and competitive pricing tactics. Both businesses trying to properly place their items in the market and customers looking to compare products need to know this information. The box plot makes the pricing disparities between various businesses more visible and gives a more accurate representation of the laptop industry's competitive environment.


    OBSERVASION:
- The laptop price range for each company is displayed in a box plot graph, where the lines extend to the minimum and highest values and the boxes represent the interquartile range (IQR). The box plots are useful for identifying the spread and central tendency (median) of prices for each company.

- A greater range of costs is exhibited by brands such as HP, Dell, and Asus, indicating that they serve both low-end and high-end consumers. Apple and Razer prices spike higher than typical values for their brands. This suggests that Apple and Razer cater more towards high-end consumers.
"""

# @title Heatmap
plt.figure(figsize=(8, 6))
corr_matrix = df[['Inches', 'CPU_Frequency (GHz)', 'RAM (GB)', 'Weight (kg)', 'Price_Euro']].corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Heatmap')
plt.show()

"""The heatmap serves as an effective tool for analyzing the interrelationships among various laptop features. By highlighting both strong and weak correlations, it aids in understanding how different specifications relate to each other and to the overall pricing of laptops. This analysis can guide product development and marketing strategies, providing insights into consumer preferences and trends in the laptop market.

    OBSERVASION:

- The heatmap illustrates the associations between the dataset's major numerical variables, such as screen size (inches), CPU frequency, RAM, weight, and price. By visualizing these interactions, the heatmap makes it simpler to identify the aspects that have the most impact on laptop prices.

- Laptops with more RAM and faster CPUs typically cost more. This is seen by the somewhat positive connection between price (Euro) and CPU frequency (GHz) and the large positive correlation between price (GB) and RAM (GB). Additionally, weight (kg) and inches show a somewhat positive link, indicating that heavier laptops are generally associated with greater screen sizes.
"""

# @title Pie Chart
import plotly.express as px
Product = df.Product.value_counts().reset_index(name='Product_count').iloc[:19]
fig = px.pie(
    data_frame=Product,
    names='Product', values='Product_count',
    hole=.1,
    color_discrete_sequence=px.colors.sequential.RdBu,
    height=600, width=1000
)
fig.update_traces(textposition='inside', textinfo='label+value')
fig.update_layout(title="Top 19 Laptop Products by Count")
fig.show()

"""This is one useful tool for visualizing the range of laptop goods in the dataset is the pie chart. It makes it easier to quickly understand which products are the most popular and draws attention to the variety found among the best options. With that, these kinds of insights can help with product development, inventory management, and marketing strategy. Stakeholders can make better informed decisions based on consumer preferences and market developments by having a clear visual representation of product distribution.

    OBSERVASION:

- The distribution of the top 19 laptop items is shown in the pie chart according to where they appear in the dataset. With the most popular devices are the MacBook Pro and MacBook Air, which demonstrate Apple's dominance in the laptop market and account for a sizable amount of the dataset.

- When compared to Apple products, other popular models, like the HP 250 G6, Dell Inspiron, and Asus Vivobook, show smaller shares, suggesting the existence of other manufacturers, albeit less frequently. Based on the graphic, it appears that a majority of the dataset's consumers prefer Apple laptops, with the remaining customers choosing from a variety of other manufacturers and models.
"""

# @title Horizontal Bar Chart
df.groupby('TypeName').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right']].set_visible(False)
plt.xlabel('Count of Laptops')
plt.ylabel('Laptop Type')
plt.title('Distribution of Laptop Types')
plt.gcf().set_size_inches(11, 6)
plt.show()

"""This is a useful visual aid for understanding the distribution of laptop types in the dataset is the horizontal bar chart. Basically, it makes quick insights into consumer preferences, market trends, and the whole range of products available possible. Stakeholders can benefit from marketing strategies, product development, and inventory management by being able to make well-informed decisions based on the representation of each type of laptop by having a clear display of the distribution.

    OBSERVASION:

- The distribution of various laptop kinds (notebook, ultrabook, gaming, 2 in 1 convertible, etc.) within the dataset is shown in this horizontal bar chart.
With the most prevalent laptop type in this dataset is a notebook, suggesting that the market represented here is dominated by classic laptop form factors.
With that, considerable amount of laptops are ultrabooks and gaming laptops, which is indicative of the rising demand for portable, powerful computers.

- Even though they are less common, the availability of 2-in-1 convertible and workstation laptops demonstrates the variety of form factors that customers can choose from. Basically, given the breadth of laptop types included in the dataset, it appears to cover a wide spectrum of use cases, from high-end gaming and convertibles to regular business machines.

**Violin Plot**
"""

# @title Violin Chart
plt.figure(figsize=(12,6))
sns.violinplot(x='TypeName', y='RAM (GB)', data=df, palette='Set2', hue = 'TypeName')
plt.title('RAM Distribution by Laptop Type')
plt.xlabel('Laptop Type')
plt.ylabel('RAM (GB)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""The gigabyte allocation of RAM among various laptop kinds is visually shown in the "RAM Distribution by Laptop Type" violin chart. It classifies laptops using an X-axis, displays RAM availability in gigabytes using a Y-axis, and illustrates RAM distribution using violin shapes. The Set2 palette is also used in the chart to clearly distinguish between different types of laptops visually. The table illustrates the range of RAM capacities found in each kind of laptop, making it possible to compare different types and spot anomalies. With its full view of the market's offers in terms of memory capacity, it is a useful tool for customers, producers, and analysts interested in laptop performance features.

    OBSERVASION:

- A number of RAM configurations across several laptop kinds are shown in the below chart, illustrating a range of configurations catered to various user needs and market sectors. It displays noticeable peaks at particular RAM numbers, indicating that these configurations fall into that categories' most popular ranges. The density of laptops with a particular RAM size is indicated by the width of each violin at a given RAM value, which aids in identifying common configurations for each kind.

- The figure makes it simple to compare different types, such gaming laptops and ultrabooks, which have different RAM quantities and a narrower range. Extremely high or low RAM capacities may indicate niche goods that are tailored to specific requirements. Consumer preferences and market changes may be reflected in the distribution patterns. For the Plot the type of Laptop that is leading or has more ram are gamibng laptops.
"""

# @title Bar Chart
plt.figure(figsize=(12, 6))
sns.countplot(x='TypeName', data=df, palette='Set2', hue = 'TypeName')
plt.title('Count of Laptops by Type')
plt.xlabel('Laptop Type')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""A bar chart called Count of Laptops by Type provides a visual representation of the prevalence of various laptop kinds in a dataset. It classifies laptops using a count plot and quantifies their counts. Rotated x-ticks make text easier to read, and the Set2 color scheme improves visual clarity. This graphic facilitates the identification of market trends and laptop inventory patterns, making it simple to evaluate popular and uncommon laptop models. All things considered, it offers data-driven market insights on laptops. On this graph Notebooks lead in the manufacturing of laptops, Ultrabook and Gaming laptops are a 2nd while the ones that don't have that much in it's type are the Workstation and Netbook.

    OBSERVASION:

- The graph makes it simple to determine the prevalence of different laptop kinds by showing each one as a separate bar. Higher numbers may be indicated by taller bars, indicating greater market availability. Differentiating laptop kinds visually using color coding using the Set2 palette facilitates rapid comparisons. Higher demand for ultrabooks or gaming laptops could be a sign of potential trends, whilst shorter bars might point to weaker demand or specialized niches.

- This visualization helps organizations or stakeholders make educated decisions by assisting with inventory management, sales strategy formulation, and understanding market dynamics. The x-tick labels are rotated to improve readability and make lengthier names easier to understand. All things considered, this data visualization is essential for understanding market dynamics, developing sales strategies, and managing inventories.

CONCLUSION:

⁤Through the process of employing all the visualizations, we have been able to formulate quite a few intriguing observations regarding aspects of laptop prices, features as well as brand and model competiveness.


- Analyzing the Central tendency of Laptop Expenses: Referring to the above given histogram, it can be observed that most of the laptops available for purchase are generally valued below Є2000 and most of them range from Є500 to Є1500, which is quite a large segment of the pricing ceiling. It is reasonable because that is the most people will want to pay be it students or merely for a decent laptop for daily use. However, there are a few expensive units priced above Є2500, but those are rare more so probably business class or premium gaming designs that only a specific clientele require.


- The Correlation of RAM and Price: Price and RAM are two parameters that exhibit a positive correlation. It is obvious due to the fact that more RAM means more cost because normally more RAM translates to adaptation performance. All manufacturers do not offer similar rates for their products and that is why not all the dots representing different laptops are arranged in a straight orientation. Such variables include reputation, processor and aesthetic appeal. There is a clear market differentiation in the underlying economy from the exhibit where products such as Apple or gaming notebooks transcend budget offering brands.

- Brand Pricing: This box plot illustrates the price comparisons across brands and shows that some companies target high-end consumers while others target a wider range. For instance, in the luxury/high-end market, Apple and Razer charge higher prices whereas hp and dell provide a large spectrum that covers both low-end and high-end users.

- Feature Correlations: As can be seen on the heatmap, there are also many interesting features correlation among laptops. For example, laptops tend to be more expensive with more ram or and faster CPU clock speed because those feature are usually performance enhancing. Heavier laptops are most likely to have a larger display size which is a consideration for someone who values portability.


- Popular Products: The pie chart also shows that the majority of the data set is represented by the Apple MacBook Pro and MacBook Air, both of which are the most popular. However, brand such as HP, Dell, Asus have their own share with the likes of HP 250 G6 and Dell Inspiron but with a smaller percentage share.

- Types of Laptops: The bar chart shows that notebooks are by far the most common type of laptop in this dataset, which makes sense because they're versatile and used by almost everyone. ⁤⁤Ultrabooks and gaming laptops are the next most popular, showing that there's also a demand for portability and power. ⁤⁤Niche types like workstations and netbooks are much less common, but they still serve specific needs.

- ⁤RAM Distribution by Laptop Type: Finally, the violin plot for RAM shows that gaming laptops tend to have the most RAM, which is expected since games need more power. ⁤⁤On the other hand, ultrabooks and other types have less RAM, but that's fine since they're meant for more basic tasks. ⁤

- ⁤Overall, this analysis gives us a pretty solid picture of how laptop prices and features vary across brands and types. ⁤⁤Most people seem to go for mid-range laptops, and features like RAM and CPU speed are major factors driving up the price. ⁤⁤There's also a clear distinction between high-end brands like Apple and more budget-friendly options, making it clear that there's something out there for everyone, depending on their needs and budget. ⁤

- Laptops Classification: Out of the available laptop types shown in this dataset, notebooks are definitely the most popular type. This is not surprising due to the fact that they are very flexible and used by virtually all categories of people. Subsequently, ultrabooks and gaming laptops occupy the third position in popularity indicating that there is also a market for power and light weight. Laptop work-stations and netbooks are such types that are rarely found, but still have their own use.

- Sources of Variation of RAM in Different Types of Laptops: Lastly, regarding the last image pertaining to the violation subplot it can be concluded that gaming laptops have the widest RAM range which is actually a common norm because games demand higher performance. On the contrary, ultrabooks and the likes have a small range of RAM, which is okay because they are designed for simpler functions.


In summary, this analysis provides us with a reasonably clear understanding of how the prices and characteristics of laptops differ by brands and types. Most people seem to favor the mid-budget laptops, with limitations such as ram and CPU speed contributing to the increased costs. Moreover, the difference is more pronounced with high brands like Apple and low-end brands, implying that there are many other options depending on one's preferences and finances.
"""